### ISSUE TITLE
Huge floats result in ParseError

### ISSUE THREAD

**Issue by fnordfish** [kgiszczak/tomlib#3]
Trying to parse https://github.com/toml-lang/toml/blob/v1.0.0-rc.1/examples/example-v0.4.0.toml, I've encountered this:

```ruby
Tomlib.load "key = 1e1000"
# => invalid value (Tomlib::ParseError)
```

Other toml libs behave like ruby and return `Float::INFINITY` instead

```ruby
TomlRB.parse "key = 1e1000"
# => {"key"=>Infinity}

1e1000
# => Infinity
```

**Comment by kgiszczak** [comment]
Thanks @fnordfish for reporting it. I just released a new version that should handle big numbers correctly.
